#!/bin/bash

##
# make clinvar rdf data
##


##
# Property
##
BASE_DIR=/data
WORK_DIR=/work
XSD_URL=https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xsd_public/ClinVar_VCV_2.0.xsd
XML_URL=https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/ClinVarVCVRelease_00-latest.xml.gz
FILE_TEMPLATE=ClinVarVCVRelease_00-latest

FORCE_CONVERT=0
NUM_PARALLEL=1

# read options
while getopts fP: OPT
do
  case $OPT in
    f)  FORCE_CONVERT=1
        ;;
    P)  NUM_PARALLEL=$OPTARG
        ;;
  esac
done
shift  $(($OPTIND - 1))


cd ${WORK_DIR}

#echo "download XML and XSD files"

now=`date "+%Y%m%d-%H%M%S"`
echo "Started wget at $now"

wget -N ${XSD_URL} 2> /wget.log
isSuccess_xsd=$?
wget -N ${XML_URL} 2>> /wget.log
isSuccess_xml=$? 

if [ ! $isSuccess_xsd -eq 0 ] || [ ! $isSuccess_xml -eq 0 ]; then
  echo "ファイルのダウンロードに失敗しました" > dev/stderr
  rm clinvar_variation/variation_archive.xsd ClinVarVariationRelease_00-latest.xml.gz
  exit 1
fi

now=`date "+%Y%m%d-%H%M%S"`
echo "Finished wget at $now"
chmod 666 $(ls)
cat /wget.log > /dev/stdout

num_of_newfiles=`egrep " saved \[[0-9]+/[0-9]+\]" /wget.log | grep -v "'.listing' saved" | wc -l `

if [ $num_of_newfiles -eq 0 ] && [ $FORCE_CONVERT -eq 0 ]; then
  echo
  echo "No RDF files were generated because no new files were found at the download site."
  exit 0
fi


now=`date "+%Y%m%d-%H%M%S"`

echo "Started convert at $now"
cd /tmp && /clinvar-rdf/bin/split ${WORK_DIR}/${FILE_TEMPLATE}.xml.gz
ls ${FILE_TEMPLATE}_*.xml.gz | xargs -n1 -P${NUM_PARALLEL} -I{} bash -c "f={}; zcat \${f} | /clinvar-rdf/docker-entrypoint.sh convert --xsd $(ls /work/*.xsd) 2>/log/\${f%%.*}.log | gzip -c >${BASE_DIR}/\${f%%.*}.ttl.gz"

grep -rnve "W" /log | grep -v "XML" > /dev/stderr

cd ${BASE_DIR} && chmod 666 $(ls) 
now=`date "+%Y%m%d-%H%M%S"`
echo "Finished convert at $now"

